name: Env

#workflow déclanché à la main
on: [push, pull_request]

env:
    PUSH: "C'est un push!"
    PULL: "C'est une pull request"

jobs:
    say_hello:
        push: 
            run_on: ubuntu-lastest
            Steps:
                - uses: actions/checkout@v3
                - name: Push
                run : echo "$PUSH"
    pull_request:
        runs-on: ubuntu-lastest
        if: ${{github.event_name == "pull_request"}}
        steps:
            - uses: actions/checkout@v3
            - name: Pull Request
            run: echo "$PULL_REQUEST